Taclef.Authentication/Areas/Admin/Models/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Web;
using Taclef.Authentication.Models;

namespace Taclef.Authentication.Areas.Admin.Models
{
	public class HomeIndexViewModel
	{
		public List<AppInfo> Consumers { get; set; } 
	}

	public class AppInfo
	{
		public string Name { get; set; }
		public string DisplayName { get; set; }
		public string Id { get; set; }
		public string SecretyKey { get; set; }
		public string WebsiteUrl { get; set; }
		public string SuccessUrl { get; set; }
		public string FailUrl { get; set; }

		public static AppInfo FromEntity(ConsumerApplication app)
		{
			var info = new AppInfo
			{
				Name = app.Name,
				DisplayName = app.DisplayName,
				Id = app.Id,
				SecretyKey = MessageSigner.GetPublicKey(app.SecretKey),
				WebsiteUrl = app.WebsiteUrl,
				SuccessUrl = app.SuccessUrl,
				FailUrl = app.FailedUrl
			};
			return info;
		}

	}
}

Taclef.Authentication/Areas/D2LAdmin/Models/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;


namespace Taclef.Authentication.Areas.D2LAdmin.Models
{
	public class HomeIndexViewModel
	{
		public List<LoginProviderDetails> Providers { get; set; }
        [DisplayName("Instance")]
		public string Provider { get; set; }
        [DisplayName("Recherche")]
		public string Keywords { get; set; }
        [DisplayName("Résultats par page")]
		public int PageCount { get; set; }

		public int PageNumber { get; set; }

		public List<UserDetails> Users { get; set; }
	    public bool HasUsers { get; set; }
	}

    public class AddUsersViewModel
    {
        public List<LoginProviderDetails> Providers { get; set; }
        [DisplayName("Instance")]
		public string Provider { get; set; }
        public List<SelectListItem> SchoolBoards { get; set; }
        [DisplayName("Conseil scolaire")]
        public string SchoolBoardId { get; set; }
        public List<SelectListItem> Schools { get; set; }
        [DisplayName("Ecole")]
        public string SchoolId { get; set; }
        public List<SelectListItem> Roles { get; set; }
        [DisplayName("Rôle")]
        public string RoleName { get; set; }
       

    }
    

	[Flags]
	public enum UserSortOrders
	{
		LastName = 0x0001,
		FirstName = 0x0002,
		Account = 0x0004,
		Email = 0x0008,
		Number = 0x0010,
		Role = 0x0020,
		Descending = 0x0100
	}
}

Taclef.Authentication/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Taclef.Authentication.Areas.Admin.Models;
using ControllerBase = Taclef.Authentication.Controllers.ControllerBase;

namespace Taclef.Authentication.Areas.Admin.Controllers
{
    public class HomeController : ControllerBase
    {
        public ActionResult Index()
        {
	        var model = new HomeIndexViewModel();
	        model.Consumers =
		        Db.ConsumerApplications.OrderBy(a => a.DisplayName).ToList().Select(AppInfo.FromEntity).ToList();
				

            return View(model);
        }

        public ActionResult Edit(string id)
        {
            throw new NotImplementedException();
        }
    }
}

Taclef.Authentication/Areas/D2LAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Taclef.Authentication.Areas.D2LAdmin.Models;
using Taclef.Authentication.LoginProviders;
using Taclef.Authentication.Models;
using Taclef.Authentication.Models.D2LLTI;

namespace Taclef.Authentication.Areas.D2LAdmin.Controllers
{
    public class HomeController : ControllerBase
    {
        // GET: D2LAdmin/Home
        public ActionResult Index(string provider = null)
        {
            var model = new HomeIndexViewModel();

            model.Providers = GetProviders();

            var loginProvider =
                GetProvider(provider);

            if (loginProvider == null)
            {
                throw new ApplicationException("No login provider found");
            }


            model.Provider = loginProvider.Name;
                model.HasUsers =
                    loginProvider.Logins.Any(
                        login =>
                            !login.User.IsDeleted &&
                            (login.User.Roles == null || login.User.Roles.Count == 0 ||
                             login.User.Roles.Any(r => r.IsStandardRole)));

                //model.Users =
                //    loginProvider.Logins.Where(login => !login.User.IsDeleted).Select(login => new UserDetails
                //    {
                //        Id = login.User.Id,
                //        Email = login.User.EmailAddress,
                //        FirstName = login.User.FirstName,
                //        LastName = login.User.LastName,
                //        // note: .MEN may throw an exception, in which case get the .EmployeeNumber and pad with zeros in the .ForEach
                //        EmployeeNumber = login.User.MEN,
                //        RoleNames = login.User.Roles.Select(r => r.Name).ToList(),
                //        Login = login.Credentials
                //    }).ToList();

                //model.Users.ForEach(u =>
                //{
                //    // Extract the D2L user account name from the login credentials
                //    var creds = Desire2LearnLtiLoginProvider.ReadCredentials(u.Login);
                //    u.Login = creds == null ? null : creds.UserId;

                //    // Figure out best role to display
                //    var role = roles.FirstOrDefault(r => u.RoleNames.Contains(r.Name));
                //    if (role != null)
                //    {
                //        u.Role = role.DisplayName;
                //    }
                //});
            


            return View(model);
        }
        
        [HttpGet]
        public ActionResult AddUsers(string provider = null)
        {
            var model = GetAddUsersViewModel(provider);
            return View(model);
        }

        private AddUsersViewModel GetAddUsersViewModel(string provider,string boardId = null)
        {
            var model = new AddUsersViewModel();
            model.Providers = GetProviders();

            var loginProvider =
                GetProvider(provider);

            if (loginProvider == null)
            {
                throw new ApplicationException("No login provider found");
            }

            model.SchoolBoards = GetSchoolBoardList(boardId);
            model.Provider = loginProvider.Name;
            model.Schools = GetSchoolList(boardId);
            model.Roles = GetStandardRoleList();
            return model;
        }

        [HttpPost]
        public ActionResult AddUsers(FormCollection formCollection, string provider)
        {
      
            var logins = formCollection["Login"].Split(',');
            var employeeNumbers = formCollection["EmployeeNumber"].Split(',');
            var roles = formCollection["RoleName"].Split(',');
            var schoolIds = formCollection["SchoolId"].Split(',');
            var schoolBoardId = formCollection["SchoolBoardId"];
            var board = Db.Boards.Find(schoolBoardId);
            // Server validation
            if (string.IsNullOrWhiteSpace(schoolBoardId))
            {
                ModelState.AddModelError("", "Le conseil scolaire est requis");

            }
            if (logins.Any(string.IsNullOrWhiteSpace))
            {
                ModelState.AddModelError("","Le nom d'utilisateur est requis");
               
            }

            if (roles.Any(string.IsNullOrWhiteSpace))
            {
                ModelState.AddModelError("", "Le rôle est requis");

            }

            for (int i = 0; i < logins.Count(); i++)
            {
                if (roles[i] == "Teacher")
                {
                    if (string.IsNullOrEmpty(schoolIds[i]))
                    {
                        if (!ModelState.ContainsKey("TeacherSchool"))
                        ModelState.AddModelError("TeacherSchool", "L'école est requise pour les enseingants");
                    }

                    if (string.IsNullOrEmpty(employeeNumbers[i]))
                    {
                        if (!ModelState.ContainsKey("TeacherEmployeeNumber"))
                            ModelState.AddModelError("TeacherEmployeeNumber", "Le numérod'employé est requise pour les enseingants");
                    }
                }
                if (roles[i] == "SchoolAdmin")
                {
                    if (string.IsNullOrEmpty(schoolIds[i]))
                    {
                        if (!ModelState.ContainsKey("SchoolAdminSchool"))
                            ModelState.AddModelError("SchoolAdminSchool", "L'école est requise pour les directeurs d'écoles");
                    }
                }
            }

            var loginProvider = GetProvider(provider);

            if (loginProvider == null)
            {
                throw new ApplicationException("No login provider found");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.FormCollection = formCollection;
                ViewBag.SchoolBoardId = schoolBoardId;
                return View(GetAddUsersViewModel(provider, schoolBoardId));
            }

            for (int i = 0; i < logins.Count(); i++)
            {
                 var school = Db.Schools.Find(schoolIds[i]);
                var credentials = Desire2LearnLtiLoginProvider.CreateCredentials(logins[i]);
                var roleName = roles[i];
                var role = Db.ApplicationRoles.FirstOrDefault(r => r.Name == roleName);
                var emplyeeNumber = !string.IsNullOrWhiteSpace(employeeNumbers[i]) && employeeNumbers[i].IsAllNumeric()
                    ? int.Parse(employeeNumbers[i])
                    : (int?) null;
                Db.UserLogins.Add(new UserLogin
                {
                    Id = Guid.NewGuid().ToString(),
                    Credentials = credentials,
                    Provider = loginProvider,
                    User = new ApplicationUser
                    {
                        Id = Guid.NewGuid().ToString(),
                        EmployeeNumber = emplyeeNumber,
                        School =  school,
                        Board = role != null && role.Name == "BoardAdmin" ? board: null,
                        Roles = role !=null? new List<ApplicationRole>
                        {
                            role
                        }:null

                    }
                });

                
            }
            Db.SaveChanges();
            return RedirectToAction("Index", new {provider});
        }

        [HttpGet]
        public ActionResult EditUser(string id)
        {
            var login = Db.UserLogins.FirstOrDefault(x => x.User.Id == id);
            if (login == null)
            {
                throw new ApplicationException(string.Format("Login with Id {0} cannot be found!", id));
            }
            ApplicationRole role = null;
            var firstOrDefault = login.User.Roles.FirstOrDefault();
            if (firstOrDefault != null)
            {
                role = firstOrDefault;
            }
            var schoolId = login.User.School == null ? "" : login.User.School.Id;
            var boardId = login.User.School != null
                ? login.User.School.Board.Id
                : login.User.Board != null ? login.User.Board.Id : "";

            var userDetail = new UserDetails
            {
                Id = login.User.Id,
                Email = login.User.EmailAddress,
                EmployeeNumber =
                    login.User.EmployeeNumber,
                FirstName = login.User.FirstName,
                LastName = login.User.LastName,
                Login = Desire2LearnLtiLoginProvider.ReadCredentials(login.Credentials).UserId,
                Role = role == null ? string.Empty : role.DisplayName,
                RoleName = role == null ? string.Empty : role.Name,
                RoleNames = login.User.Roles.Select(r => r.Name).ToList(),
                Roles = GetStandardRoleList(),
                SchoolBoards = GetSchoolBoardList(boardId),
                Schools = GetSchoolList(boardId, schoolId),
                SchoolBoardId =
                    login.User.School == null
                        ? (login.User.Board == null ? "" : login.User.Board.Id)
                        : login.User.School.Board.Id,
                SchoolId = login.User.School == null ? "" : login.User.School.Id
            };


            return View(userDetail);
        }

        [HttpPost]
        public ActionResult EditUser(UserDetails userDetails)
        {
            var loginToUpddate = Db.UserLogins.FirstOrDefault(x => x.User.Id == userDetails.Id);
            if (loginToUpddate == null)
            {
                throw new ApplicationException(string.Format("Login with Id {0} cannot be found!", userDetails.Id));
            }


            var schoolId = loginToUpddate.User.School == null ? "" : loginToUpddate.User.School.Id;

Taclef.Authentication/Controllers/D2LController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Taclef.Authentication.LoginProviders;
using Taclef.Authentication.Models;

namespace Taclef.Authentication.Controllers
{
	public class D2LController : ControllerBase
	{
		public ApplicationUser GetOrCreateUser(AuthRequestModel authRequest)
		{
			var provider =
				Db.LoginProviders.FirstOrDefault(p => p.DerivedKey == authRequest.ProviderDerivedKey && p.ProviderType == "D2L-LTI");
			if (provider == null) throw new ApplicationException("Could not find a Login Provider corresponding to the request: " + authRequest.ProviderDerivedKey);

			var login =
				provider.Logins.FirstOrDefault(p => p.Credentials == authRequest.ProviderCredentials);

			ApplicationUser user;

			if (login == null)
			{
				// determine if a user already exists for this login
				user = Db.ApplicationUsers.FirstOrDefault(u => u.EmailAddress == authRequest.User.Email);

				if (user == null)
				{
					// create a new user
					user = Db.CreateAdd<ApplicationUser>();
				}

				// create new login for user
				login = Db.CreateAdd<UserLogin>(u =>
				{
					u.User = user;
					u.Provider = provider;
					u.Credentials = authRequest.ProviderCredentials;
				});
			}
			else
			{
				user = login.User;
			}

			if (user.IsDeleted) throw new ApplicationException("The user associated with these credentials has been deleted");
			if (user.IsLocked) throw new ApplicationException("The user associated with these credentials has been locked out");

			// update user details
			user.FirstName = authRequest.User.FirstName;
			user.LastName = authRequest.User.LastName;
			user.EmailAddress = authRequest.User.Email;

			Db.SaveChanges();
			return user;
		}

		[HttpPost]
		public ActionResult Launch(string id, FormCollection form)
		{
			var model = new AuthResponseModel();
			try
			{
				if (string.IsNullOrWhiteSpace(id)) return View("Error");
				var app = Db.ConsumerApplications.FirstOrDefault(a => a.Name == id);
				if (app == null) return View("Error");
				model.Url = app.FailedUrl;

				var loginProvider = new Desire2LearnLtiLoginProvider();
				var authRequest = new AuthRequestModel();
				loginProvider.ProcessLoginRequest(form, Request.QueryString, authRequest);
				var user = GetOrCreateUser(authRequest);
				var response = AuthResponseMessage.CreateFor(user);
				model.Message = SerializeToJson(response);
				model.Signature = MessageSigner.SignMessage(model.Message, app.SecretKey);
				model.Url = app.SuccessUrl;
			}
			catch (Exception exception)
			{
				model.Error = exception.ToString();
				model.Signature = null;
				model.Message = exception.Message;
				model.LtiData = form.AllKeys.ToDictionary(k => k, k => form[k]);
			}

			return View("AuthResponse", model);
		}
	}
}

Taclef.Authentication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Taclef.Authentication.Models;

namespace Taclef.Authentication.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View(new D2LLoginTestViewModel());
		}
	}
}

Taclef.Authentication/Views/Home/Index.cshtml
@model Taclef.Authentication.Models.D2LLoginTestViewModel


@*@using (Html.BeginForm("Launch", "D2L")) {
	@Html.Hidden("id", "d2l-cforp")
	
	<table>
		<tr>
			<td>@Html.LabelFor(m => m.Login)</td>
			<td>@Html.EditorFor(m => m.Login)</td>
		</tr>
		<tr>
			<td>@Html.LabelFor(m => m.FirstName)</td>
			<td>@Html.EditorFor(m => m.FirstName)</td>
		</tr>
		<tr>
			<td>@Html.LabelFor(m => m.LastName)</td>
			<td>@Html.EditorFor(m => m.LastName)</td>
		</tr>
		<tr>
			<td>@Html.LabelFor(m => m.Email)</td>
			<td>@Html.EditorFor(m => m.Email)</td>
		</tr>
		<tr>
			<td>@Html.LabelFor(m => m.SelectedSchool)</td>
			<td>@Html.DropDownListFor(m => m.SelectedSchool, Model.Schools.Select(s => new SelectListItem { Text = s.Name, Value = s.Id}))
		</tr>
		<tr>
			<td>@Html.LabelFor(m => m.SelectedSchool)</td>
			<td>@Html.DropDownListFor(m => m.SelectedSchool, Model.Schools.Select(s => new SelectListItem { Text = s.Name, Value = s.Id}))
		</tr>
		<tr>
			<td>@Html.LabelFor(m => m.SelectedRole)</td>
			<td>
				@foreach (var role in Model.Roles) {
					<label>
						<input type="checkbox" name="@Html.NameFor(m => m.SelectedRole)" value="@role.Id"/>
						@role.Name
					</label>
				}
			</td>
		</tr>
	</table>
	<input type="submit" value="Login"/>
}*@


@{
	//ViewBag.Key = MessageSigner.CreateKey();
}
@*
	<h3>Private Key</h3>
<pre>@ViewBag.Key</pre>
<h3>Public Key</h3>
<pre>@MessageSigner.GetPublicKey(ViewBag.Key)</pre>
<h3>Signature</h3>
<pre>@MessageSigner.SignMessage("hello world", ViewBag.Key)</pre>
Signature is valid: @MessageSigner.VerifySignature("hello world", MessageSigner.SignMessage("hello world", ViewBag.Key), MessageSigner.GetPublicKey(ViewBag.Key))
*@


<form method="post" id="LtiRequestForm" name="LtiRequestForm" action="@Url.Action("Launch", "D2L", new { id = "taclef-quiz"})" enctype="application/x-www-form-urlencoded">
<input type="hidden" name="launch_presentation_locale" value="EN-US__">
<input type="hidden" name="tool_consumer_instance_guid" value="">
<input type="hidden" name="tool_consumer_instance_name" value="">
<input type="hidden" name="tool_consumer_instance_description" value="">
<input type="hidden" name="tool_consumer_instance_contact_email" value="">
<input type="hidden" name="tool_consumer_info_version" value="10.3.0 SP17">
<input type="hidden" name="tool_consumer_info_product_family_code" value="desire2learn">
<input type="hidden" name="context_id" value="164993">
<input type="hidden" name="context_title" value="Vote Compass Sandbox">
<input type="hidden" name="context_label" value="Vote Compass Sandbox">
<input type="hidden" name="context_type" value="">
<input type="hidden" name="user_id" value="LCL_1906">
<input type="hidden" name="roles" value="Student,Instructor,Administrator">
<input type="hidden" name="lis_person_name_given" value="Stephen">
<input type="hidden" name="lis_person_name_family" value="Bognar">
<input type="hidden" name="lis_person_name_full" value="Stephen Bognar">
<input type="hidden" name="lis_person_contact_email_primary" value="stephen.bognar@cforp.ca">
<input type="hidden" name="ext_d2l_username" value="stephen.bognar">
<input type="hidden" name="ext_d2l_orgdefinedid" value="stephen.bognar">
<input type="hidden" name="ext_d2l_role" value="LMS_Admin">
<input type="hidden" name="ext_tc_profile_url" value="https://cforp.desire2learn.com/d2l/api/ext/1.0/lti/tcservices">
<input type="hidden" name="ext_d2l_token_id" value="4385032">
<input type="hidden" name="ext_d2l_link_id" value="73">
<input type="hidden" name="ext_d2l_token_digest" value="ThiSNhc1o+5BMFZVX1xoGDTkM04=">
<input type="hidden" name="resource_link_id" value="204948590">
<input type="hidden" name="resource_link_title" value="Civics: Open Mind Maps">
<input type="hidden" name="resource_link_description" value="">
<input type="hidden" name="lis_result_sourcedid" value="3095b279-39d6-4734-b3a7-a1a5b2a123a4">
<input type="hidden" name="lis_outcome_service_url" value="https://cforp.desire2learn.com/d2l/le/lti/Outcome">
<input type="hidden" name="lti_version" value="LTI-1p0">
<input type="hidden" name="lti_message_type" value="basic-lti-launch-request">
<input type="hidden" name="oauth_version" value="1.0">
<input type="hidden" name="oauth_nonce" value="123616505">
<input type="hidden" name="oauth_timestamp" value="1429734292">
<input type="hidden" name="oauth_signature_method" value="HMAC-SHA1">
<input type="hidden" name="oauth_consumer_key" value="elolms">
<input type="hidden" name="oauth_callback" value="about:blank">
<input type="hidden" name="oauth_signature" value="MZ0FFU79oLJrLynezuB5vqSwwMo=">
<input type="submit" name="ext_basiclti_submit" value="Launch Endpoint with BasicLTI Data">
</form>

@section scripts {
<script>
	$(function() {
		$('form#LtiRequestForm').submit();
	});
</script>	
}